# Generated by Django 4.2.2 on 2024-08-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet_addrestt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wallet_addrestt',
            new_name='wallet_address',
        ),
    ]
