# Generated by Django 4.2.2 on 2024-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_wallet_addrestt_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
